//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int ProductId { get; set; }
        public string AlertCategory { get; set; }
        public string Metric { get; set; }
        public string Value { get; set; }
        public string Severity { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> LastActiveTime { get; set; }
        public string Instance { get; set; }
        public string Database { get; set; }
        public string Table { get; set; }
        public string Summary { get; set; }
    
        public virtual RegisteredProduct RegisteredProduct { get; set; }
    }
}
