//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log
    {
        public int ID { get; set; }
        public string TagID { get; set; }
        public string TagName { get; set; }
        public string TagDescription { get; set; }
        public Nullable<int> TagProductID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
        public string Changes { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public Nullable<int> DatabaseID { get; set; }
        public string Exception { get; set; }
        public Nullable<int> SourceProductID { get; set; }
    
        public virtual Databas Databas { get; set; }
        public virtual Instance Instance { get; set; }
    }
}
