//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Databas
    {
        public Databas()
        {
            this.Database_RegisteredProduct = new HashSet<Database_RegisteredProduct>();
            this.Audit_Log = new HashSet<Audit_Log>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime UTCFirstSeen { get; set; }
        public System.DateTime UTCLastSeen { get; set; }
        public string Owner { get; set; }
        public int InstanceID { get; set; }
    
        public virtual ICollection<Database_RegisteredProduct> Database_RegisteredProduct { get; set; }
        public virtual ICollection<Audit_Log> Audit_Log { get; set; }
        public virtual Instance Instance { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
