//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string KeyString { get; set; }
        public string Repository { get; set; }
        public int Status { get; set; }
        public bool IsTrial { get; set; }
        public bool IsPermanent { get; set; }
        public bool IsEnterprise { get; set; }
        public bool LicenseAboutToExpire { get; set; }
        public System.DateTime Expiration { get; set; }
        public int DaysToExpire { get; set; }
        public int LicensedServers { get; set; }
        public int MonitoredServers { get; set; }
        public string Comments { get; set; }
        public string WebURL { get; set; }
        public string RestURL { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual RegisteredProduct RegisteredProduct { get; set; }
    }
}
