//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredProduct
    {
        public RegisteredProduct()
        {
            this.Database_RegisteredProduct = new HashSet<Database_RegisteredProduct>();
            this.Instance_RegisteredProduct = new HashSet<Instance_RegisteredProduct>();
            this.Licenses = new HashSet<License>();
            this.Permissions = new HashSet<Permission>();
            this.ProductWidgetConfigs = new HashSet<ProductWidgetConfig>();
            this.Alerts_Metadata = new HashSet<Alerts_Metadata>();
            this.Alerts = new HashSet<Alert>();
            this.RegisteredProductURLs = new HashSet<RegisteredProductURL>();
            this.Roles = new HashSet<Role>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string RegisteringUser { get; set; }
        public System.DateTime RegistrationDateTime { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
        public string InstanceName { get; set; }
        public string Version { get; set; }
        public string Location { get; set; }
        public string ConnectionUser { get; set; }
        public string ConnectionPassword { get; set; }
        public string Status { get; set; }
        public string JarFile { get; set; }
        public string Description { get; set; }
        public string DefaultPage { get; set; }
        public string RestFile { get; set; }
        public bool IsLoadable { get; set; }
        public Nullable<int> Order { get; set; }
        public string ProductServicesHost { get; set; }
        public int ProductServicesPort { get; set; }
        public Nullable<bool> IsMigrating { get; set; }
        public Nullable<int> MigrationStatus { get; set; }
        public bool IsTaggable { get; set; }
        public bool IsRedirectable { get; set; }
    
        public virtual ICollection<Database_RegisteredProduct> Database_RegisteredProduct { get; set; }
        public virtual ICollection<Instance_RegisteredProduct> Instance_RegisteredProduct { get; set; }
        public virtual ICollection<License> Licenses { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<ProductWidgetConfig> ProductWidgetConfigs { get; set; }
        public virtual ICollection<Alerts_Metadata> Alerts_Metadata { get; set; }
        public virtual ICollection<Alert> Alerts { get; set; }
        public virtual ICollection<RegisteredProductURL> RegisteredProductURLs { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
