//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSRSReportConfiguration
    {
        public int ID { get; set; }
        public string ReportInstance { get; set; }
        public string ReportURL { get; set; }
        public string WebServiceURL { get; set; }
        public string ReportUserName { get; set; }
        public string ReportUserPassword { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string Version { get; set; }
    }
}
