//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Databases = new HashSet<Databas>();
            this.Instances = new HashSet<Instance>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual RegisteredProduct RegisteredProduct { get; set; }
        public virtual ICollection<Databas> Databases { get; set; }
        public virtual ICollection<Instance> Instances { get; set; }
    }
}
