//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Permissions = new HashSet<Permission>();
            this.UserGroups = new HashSet<UserGroup>();
            this.UsersProductWidgetConfigs = new HashSet<UsersProductWidgetConfig>();
        }
    
        public int ID { get; set; }
        public string Account { get; set; }
        public string UserType { get; set; }
        public string SID { get; set; }
        public bool Enabled { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        public virtual ICollection<UsersProductWidgetConfig> UsersProductWidgetConfigs { get; set; }
    }
}
