//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersProductWidgetConfig
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ProductWidgetConfigId { get; set; }
        public string Settings { get; set; }
    
        public virtual ProductWidgetConfig ProductWidgetConfig { get; set; }
        public virtual User User { get; set; }
    }
}
