//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewConfig
    {
        public ViewConfig()
        {
            this.ViewColumns = new HashSet<ViewColumn>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int TabOrder { get; set; }
    
        public virtual ICollection<ViewColumn> ViewColumns { get; set; }
    }
}
