//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewColumn
    {
        public ViewColumn()
        {
            this.ViewColumnWidgets = new HashSet<ViewColumnWidget>();
        }
    
        public int ID { get; set; }
        public int ViewID { get; set; }
        public string Width { get; set; }
        public int ColumnOrder { get; set; }
        public string Settings { get; set; }
    
        public virtual ICollection<ViewColumnWidget> ViewColumnWidgets { get; set; }
        public virtual ViewConfig ViewConfig { get; set; }
    }
}
